esphome:
  name: smarties
  platform: ESP8266
  board: d1_mini

wifi:
  ssid: Tristan Moreau
  password: totototo

logger:
ota:
api:

sensor:
  - platform: adc
    pin: A0
    name: "Weight Sensor"
    update_interval: 10s
    id: weight_sensor
    unit_of_measurement: "Ohm"
    filters:
      - lambda: return 10000 * (5 - x) / x;

binary_sensor:
  - platform: gpio
    pin: D2
    name: "Sound level"
    filters:
      - delayed_off: 1s
